name: Basil-Malik Photography
favicon: null
layout_spectrum: 0.15180828096345067
typography_spectrum: 0.12378952419385314
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7824899896513671
  lightness: 0.25594759499654174
  saturation: 0.7353910887613893
  rhythmicContrast: 0.00931827025488019
purpose: []
