name: Basil-Malik Photography
favicon: null
layout_spectrum: 0.24573
typography_spectrum: 0.13584
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#242424'
    - '#6f6f6f'
    - '#8a8a8a'
    - '#e8e8e8'
    - '#bbbbbb'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
